create table if not exists game_dividend_payouts (
    id bigint generated by default as identity primary key,
    season_id bigint not null,
    user_id bigint not null,
    position_id bigint not null,
    trend_run_id bigint not null,
    rank_at_payout integer not null,
    dividend_rate_basis_points integer not null,
    amount_points bigint not null,
    created_at timestamp with time zone not null,
    constraint uk_game_dividend_payouts_season_position_run unique (season_id, position_id, trend_run_id),
    constraint fk_game_dividend_payouts_season foreign key (season_id) references game_seasons (id),
    constraint fk_game_dividend_payouts_user foreign key (user_id) references app_users (id),
    constraint fk_game_dividend_payouts_position foreign key (position_id) references game_positions (id)
);

create index if not exists idx_game_dividend_payouts_season_run
    on game_dividend_payouts (season_id, trend_run_id);
